export * from './client'
export * from './types'
export * from './platos'
export * from './insumos'
export * from './menus'
export * from './reservas'
export * from './proveedores'
export * from './compras'
export * from './pagos'
export * from './becas'

// Re-export named APIs for convenient imports
export { platosApi } from './platos'
export { insumosApi } from './insumos'
export { menusApi } from './menus'
export { reservasApi } from './reservas'
export { proveedoresApi } from './proveedores'
export { comprasApi } from './compras'
export { pagosApi } from './pagos'
export { becasApi } from './becas'
